//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_MiSide : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.miSide_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.miSide_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.miSide_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.miSide_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.miSide_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.miSide_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.miSide_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 WSAD_Move
        {
            get
            {
                return SteamVR_Actions.miSide_WSAD_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shift_Run
        {
            get
            {
                return SteamVR_Actions.miSide_Shift_Run;
            }
        }
        
        public virtual SteamVR_Action_Boolean MouseLeftLick
        {
            get
            {
                return SteamVR_Actions.miSide_MouseLeftLick;
            }
        }
        
        public virtual SteamVR_Action_Boolean E_Interact
        {
            get
            {
                return SteamVR_Actions.miSide_E_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Q_Command
        {
            get
            {
                return SteamVR_Actions.miSide_Q_Command;
            }
        }
        
        public virtual SteamVR_Action_Boolean Space_Jump
        {
            get
            {
                return SteamVR_Actions.miSide_Space_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Enter
        {
            get
            {
                return SteamVR_Actions.miSide_Enter;
            }
        }
        
        public virtual SteamVR_Action_Boolean ESC_Menu
        {
            get
            {
                return SteamVR_Actions.miSide_ESC_Menu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MouseMove_Rotate
        {
            get
            {
                return SteamVR_Actions.miSide_MouseMove_Rotate;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftArrow
        {
            get
            {
                return SteamVR_Actions.miSide_LeftArrow;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightArrow
        {
            get
            {
                return SteamVR_Actions.miSide_RightArrow;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpArrow
        {
            get
            {
                return SteamVR_Actions.miSide_UpArrow;
            }
        }
        
        public virtual SteamVR_Action_Boolean DownArrow
        {
            get
            {
                return SteamVR_Actions.miSide_DownArrow;
            }
        }
        
        public virtual SteamVR_Action_Boolean Hold_PinUI
        {
            get
            {
                return SteamVR_Actions.miSide_Hold_PinUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleVRIK
        {
            get
            {
                return SteamVR_Actions.miSide_ToggleVRIK;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab_Left
        {
            get
            {
                return SteamVR_Actions.miSide_Grab_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab_Right
        {
            get
            {
                return SteamVR_Actions.miSide_Grab_Right;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticLeft
        {
            get
            {
                return SteamVR_Actions.miSide_HapticLeft;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticRight
        {
            get
            {
                return SteamVR_Actions.miSide_HapticRight;
            }
        }
    }
}
